#
#  █████╗ ██╗      █████╗  ██████╗██╗████████╗████████╗██████╗ ██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██║╚══██╔══╝╚══██╔══╝██╔══██╗╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██║   ██║      ██║   ██████╔╝ ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██║   ██║      ██║   ██╔══██╗  ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║   ██║      ██║   ██║  ██║   ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝   ╚═╝      ╚═╝   ╚═╝  ╚═╝   ╚═╝
#
# Alacritty Config File by Arfan Zubi


[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "None"
resize_increments = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Semibold" }
size = 13

[cursor]
style = { blinking = "On" }

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Key1"
mods = "Control"
